"""Public exports for the swos-core package."""

from importlib.metadata import PackageNotFoundError, version

from swos_core.api import DeviceAdapter, SwOSDevice
from swos_core.errors import (
    DeviceDetectionError,
    InvalidOperationError,
    ManagementStateUncertainError,
    UnsupportedFeatureError,
)
from swos_core.models import (
    AclRule,
    AclVlanTagMode,
    AddressMode,
    DeviceCapabilities,
    DeviceConnection,
    DeviceIdentity,
    DeviceNameUpdate,
    ForcedPortNegotiation,
    ForwardingInfo,
    ForwardingMatrixUpdate,
    ForwardingMirroringUpdate,
    ForwardingPortPolicyUpdate,
    HostEntry,
    HostEntryType,
    IgmpGroup,
    IgmpInfo,
    IgmpVersion,
    OperationResult,
    PacketSizeStatistics,
    PasswordUpdate,
    PoeMode,
    PoeStatus,
    PortConfigurationUpdate,
    PortErrorStatistics,
    PortForwardingInfo,
    PortInfo,
    PortNameUpdate,
    PortRateStatistics,
    PortStatistics,
    PortTrafficStatistics,
    PortVlanInfo,
    PortVlanPolicyUpdate,
    RstpBridgeUpdate,
    RstpCostMode,
    RstpInfo,
    RstpPortEnableUpdate,
    RstpPortInfo,
    RstpPortType,
    RstpProtocol,
    RstpRole,
    RstpState,
    SafetyWarning,
    SfpInfo,
    SnmpInfo,
    SnmpMetadataUpdate,
    SystemConfigurationUpdate,
    SystemHealth,
    SystemInfo,
    SystemManagementInfo,
    VlanEgressMode,
    VlanInfo,
    VlanMembershipMode,
    VlanMode,
    VlanPortMembership,
    VlanReceiveMode,
)
from swos_core.plugins import DevicePlugin, PluginRegistry, SupportRecord
from swos_core.safety import FirmwareSafetyPolicy

try:
    __version__ = version("swos-core")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "AclRule",
    "AclVlanTagMode",
    "AddressMode",
    "DeviceAdapter",
    "DeviceCapabilities",
    "DeviceConnection",
    "DeviceDetectionError",
    "DeviceIdentity",
    "DeviceNameUpdate",
    "DevicePlugin",
    "FirmwareSafetyPolicy",
    "ForcedPortNegotiation",
    "ForwardingInfo",
    "ForwardingMatrixUpdate",
    "ForwardingMirroringUpdate",
    "ForwardingPortPolicyUpdate",
    "HostEntry",
    "HostEntryType",
    "IgmpGroup",
    "IgmpInfo",
    "IgmpVersion",
    "InvalidOperationError",
    "ManagementStateUncertainError",
    "OperationResult",
    "PacketSizeStatistics",
    "PasswordUpdate",
    "PluginRegistry",
    "PoeMode",
    "PoeStatus",
    "PortConfigurationUpdate",
    "PortErrorStatistics",
    "PortForwardingInfo",
    "PortInfo",
    "PortNameUpdate",
    "PortRateStatistics",
    "PortStatistics",
    "PortTrafficStatistics",
    "PortVlanInfo",
    "PortVlanPolicyUpdate",
    "RstpBridgeUpdate",
    "RstpCostMode",
    "RstpInfo",
    "RstpPortEnableUpdate",
    "RstpPortInfo",
    "RstpPortType",
    "RstpProtocol",
    "RstpRole",
    "RstpState",
    "SafetyWarning",
    "SfpInfo",
    "SnmpInfo",
    "SnmpMetadataUpdate",
    "SupportRecord",
    "SwOSDevice",
    "SystemConfigurationUpdate",
    "SystemHealth",
    "SystemInfo",
    "SystemManagementInfo",
    "UnsupportedFeatureError",
    "VlanEgressMode",
    "VlanInfo",
    "VlanMembershipMode",
    "VlanMode",
    "VlanPortMembership",
    "VlanReceiveMode",
    "__version__",
]
